/* empty css                      */import{a as v,S as E,i as s}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const q="57664236-869314b2394556b9e8d04d1c8",M="https://pixabay.com/api/";async function h(o,t){return(await v.get(M,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const g=document.querySelector("#gallery"),m=document.querySelector("#loader"),p=document.querySelector("#load-more");let R=new E(".gallery a",{captionsData:"alt",captionDelay:250});function f(o){const t=o.map(({webformatURL:i,largeImageURL:l,tags:e,likes:r,views:n,comments:b,downloads:P})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${l}">
            <img class="gallery-image" src="${i}" alt="${e}" />
          </a>
          <ul class="gallery-info">
            <li><h3>Likes</h3><p>${r}</p></li>
            <li><h3>Views</h3><p>${n}</p></li>
            <li><h3>Comments</h3><p>${b}</p></li>
            <li><h3>Downloads</h3><p>${P}</p></li>
          </ul>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",t),R.refresh()}function B(){g.innerHTML=""}function y(){m.classList.remove("is-hidden")}function L(){m.classList.add("is-hidden")}function w(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}const S=document.querySelector("#search-form"),$=document.querySelector("#load-more");let c="",a=1,d=1;const O=15;S.addEventListener("submit",x);$.addEventListener("click",A);async function x(o){if(o.preventDefault(),c=o.currentTarget.elements.searchQuery.value.trim(),c===""){s.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}a=1,B(),u(),y();try{const t=await h(c,a);if(t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}d=Math.ceil(t.totalHits/O),f(t.hits),a<d?w():s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{L(),S.reset()}}async function A(){a+=1,u(),y();try{const o=await h(c,a);f(o.hits);const t=document.querySelector(".gallery-item");if(t){const i=t.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}a<d?w():(u(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}finally{L()}}
//# sourceMappingURL=index.js.map
